name: CI-CD with kind

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: demo-cluster
      KIND_VERSION: v0.23.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kind
        uses: helm/kind-action@v1.10.0
        with:
          version: ${{ env.KIND_VERSION }}
          cluster_name: ${{ env.CLUSTER_NAME }}

      - name: Create jfrog-creds secret
        run: |
          kubectl create secret docker-registry jfrog-creds \
            --docker-server=${{ secrets.ARTIFACTORY_URL }} \
            --docker-username=${{ secrets.ARTIFACTORY_USERNAME }} \
            --docker-password=${{ secrets.ARTIFACTORY_PASSWORD }} \
            --docker-email=viveksaireddykoduru@gmail.com

      - name: Deploy Deployment YAML
        run: |
          kubectl apply -f deployment.yaml

      - name: Deploy Service YAML
        run: |
          kubectl apply -f service.yaml

      - name: Wait for deployment rollout
        run: |
          kubectl rollout status deployment/my-app

      - name: Test service using port-forward
        run: |
          kubectl wait --for=condition=ready pod \
            -l app=my-app \
            --timeout=60s

          NODE_PORT=$(kubectl get svc my-app-service -o jsonpath='{.spec.ports[0].nodePort}')

          echo "NodePort = $NODE_PORT"

          kubectl port-forward svc/my-app-service 8080:$NODE_PORT &
          sleep 5

          curl http://localhost:8080/api/hello
