name: Deploy from JFrog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

      - name: Create (or update) jfrog image pull secret
        run: |
          kubectl delete secret jfrog-creds --ignore-not-found

          kubectl create secret docker-registry jfrog-creds \
            --docker-server=${{ secrets.ARTIFACTORY_URL }} \
            --docker-username=${{ secrets.ARTIFACTORY_USERNAME }} \
            --docker-password=${{ secrets.ARTIFACTORY_PASSWORD }} \
            --docker-email=none@example.com

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Check deployment rollout
        run: |
          kubectl rollout status deployment/my-app

      - name: Get service info
        run: |
          kubectl get svc my-app-service
